name: CI to Docker Hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for tags vX.X.X
  push:
    tags:
      - "v*.*.*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow call reusable workflow docker-build
  build:
    uses: rubensa/docker-ubuntu-tini/.github/workflows/docker-build.yml@master
    with:
      DOCKER_REPOSITORY_NAME: rubensa
      DOCKER_IMAGE_NAME: ubuntu-tini-dev-k8s
      DOCKER_IMAGE_TAG: 18.04
    secrets: inherit
